config/routes.rb
HackerNews::Application.routes.draw do

  root 'posts#index'

  resources :users

  resources :posts do
    resources :comments
  end

  resources :sessions, only: [:new, :create, :destroy]

  get 'login' => 'sessions#new', as: :login

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
  end

  def show
    @post = Post.where(post_id: params[:id]).first
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def create
    @post = (params[:post_id])
    @comment = Comment.create(user_id: session[:user_id], post_id: params[:post_id], text: params[:comment][:text])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
  end

  def create
    @post = Post.create(
      user_id: session[:user_id],
      url: params[:post][:url],
      title: params[:post][:title],
      body: params[:post][:body] )

    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(email: params[:session][:email]).first
    # binding.pry

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
      # binding.pry
    else
      render 'new'
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "new"
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?
    @user = User.where(id: session[:user_id]).first
  end
end

app/views/comments/edit.html.erb
<%= form_for :comment, url: ([@post, @post.comments.build]), method: :patch do |f| %>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
Hacker News blah blah<br>

<% if current_user? %>
<%=	link_to "Sign Out", session_path(session), method: :delete, data: { confirm: 'Are you sure you want to poodle?' } %>
<%= link_to "Post", new_post_path %>
<%	else %>
<%=	link_to "Sign In", login_path %>
<%=	link_to "Sign Up", new_user_path %>
<% end %>

<ul>
  <% @posts.each do |post| %>
    <li><div><%= link_to "#{post.title}", "http://#{post.url}" %><br>
        <%= link_to "view post", post_path(post) %>
        <%= link_to "edit post", edit_post_path(post) %>
        <%= link_to "delete post", post_path(post), method: :delete, data: { confirm: 'Sure?!' } %>
    </div>

    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %><br>
  </p>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
URL: <%= link_to 'Here is your fucking button', "http://#{@post.url}" %><br><br>

Title: <%= @post.title %><br>
Body: <%= @post.body %><br>
<%= link_to "edit post", edit_post_path(@post) %>
<p>Comments:</p>
<% @comments.each do |comment| %>
  <p><%= comment.text %></p>
  <%= link_to "edit comment", edit_post_comment_path(comment.post, comment) %>
  <%= link_to 'delete comment', [comment.post, comment], method: :delete, data: { confirm: 'YES?!' } %>
<% end %>

<%= form_for ([@post, @post.comments.build]) do |f| %>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'home', root_path %>

app/views/users/new.html.erb
<h4>Please sign up below</h4>

<%= form_for :user, url: users_path do |f| %>
  <p>
      <%= f.label :email  %><br>
      <%= f.text_field :email, :placeholder => "email" %>
  </p>
  <p>
      <%= f.label :password %><br>
      <%= f.password_field :password, :placeholder => "password" %>
  </p>
  <p>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, :placeholder => "confirm password" %>
  </p>
  <p>
      <%= f.submit %>
  </p>
<% end %>